version: '3'
services:
  db:
    image: postgres:9.6.16
    ports:
      - "5432:5432" 
    volumes:
      - postgresql_data:/var/lib/postgresql/data
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: "development"
      REDIS_URL: "redis://redis:6379/12"
      ELASTICSEARCH_URL: "http://elasticsearch:9200"
    depends_on:
      - db
      - elasticsearch
      - webpacker_dev_server
  webpacker_dev_server:
    build: .
    command: bash -c "./bin/webpack_dev_server -p 3035"
    volumes:
      - .:/app
    ports:
      - "3035:3035"
  redis:
    image: redis
    volumes:
      - ../../tmp/db:/var/lib/redis/data
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.0.1
    container_name: elasticsearch
    environment:
      - node.name=es01
      - discovery.seed_hosts=es01
      - cluster.initial_master_nodes=es01
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=false
      - "ES_JAVA_OPTS=-Xms128m -Xmx128m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
volumes:
  postgresql_data: